CIGI-527: Implement newsletter page
CIGIHub/cigionline pull request #1091
Opened 2021-03-09 18:21 UTC by johnbxu

#### Description of changes
resolves CIGIHub/cigi-tickets#527

- Images won't load because the urls are hardcoded for production

2021-03-12 02:30 UTC, gabrieltanchen reviewed
I'm a little confused as to what's going on with the images. The URL is hardcoded for production but it's using Wagtail image paths?

2021-03-12 13:53 UTC, johnbxu commented
> The URL is hardcoded for production but it's using Wagtail image paths?

The Wagtail image path is relative, but the html needs to use the production path because it's the one copied to mailchimp. On the Drupal site there is a function in the theme hook to replace all admin urls with non-admin. I could do that instead?

2021-03-12 16:34 UTC, gabrieltanchen commented
Oh okay I see where you're hardcoding the domain, and I assume this is why you asked if editors will still be accessing from admin.cigionline.org?

You should be able to use the domain of the root site here. Even for admin.cigionline.org, it'll still be accessing the production database which will have the root site as www.cigionline.org.

2021-03-12 18:11 UTC, johnbxu commented
Ah ok, good to know.

2021-03-13 00:41 UTC, johnbxu commented
Updated to use root domain

2021-03-15 16:03 UTC, gabrieltanchen requested changes
The site in the request doesn't seem to be the default site, I believe it's returning `None` since the request domain doesn't match. You should be able to query for the default Site in the `get_context` method, then use the `root_url` property: https://docs.wagtail.io/en/stable/reference/pages/model_reference.html#wagtail.core.models.Site.root_url

Using the `image_url` or image object should be cleaned up between the `get_context` method and the block templates.

2021-03-15 16:03 UTC, gabrieltanchen commented on streams/blocks.py
> +                context['url'] = f'https://www.cigionline.org{content_page.url_path}'
Beware of using `url_path` in links, since it contains the home slug as well. Can this also check for the root domain?

2021-03-16 17:44 UTC, johnbxu commented
Used site root_url from context

2021-03-17 15:43 UTC, gabrieltanchen commented
@johnbxu plot twist on this. After fixing some stuff with the social meta tags, I don't think we need `root_url` here at all. Just let the image urls get generated as normal, and they should pull from the root domain automatically because of the S3 settings on production.

Can you fix this to remove the root url code? If we run into any issues when setting up admin we can fix it then.

2021-03-17 17:45 UTC, johnbxu commented
Removed root_url from images, and removed social links as per https://github.com/CIGIHub/cigi-tickets/issues/546

2021-03-18 14:32 UTC, gabrieltanchen approved these changes

2021-03-18 14:32 UTC, merged