CIGI-611: Event calendar timezone
CIGIHub/cigionline pull request #1661
Opened 2021-07-19 13:04 UTC by yang-wang-ds

#### Description of changes
resolves CIGIHub/cigi-tickets#611

- Fixed google calendar url formatting
- Added support for commonly used timezones

#### Pull Request checklist
This checklist needs to be completed before assigning reviewers. If the checklist will not be completed, please comment with the reason.
- [ ] Have you reviewed your own code changes?
- [ ] Has the issue owner reviewed your changes?
- [ ] Have you given the PR a descriptive title?
- [ ] Have you described your changes above? Always include screenshots if applicable.
- [ ] Have you pushed your latest commit to this branch?

---
#### Code Review checklist
This checklist should be completed if applicable before approving the pull request.
- [ ] Have you reviewed the code changes?
- [ ] Have you tested the changes on Google Chrome?
- [ ] Have you tested the changes on Safari?
- [ ] Have you tested the changes on Microsoft Edge (non-Chromium)?
- [ ] Have you tested the changes on iOS?
- [ ] Have you tested the changes on Android?

2021-07-20 17:06 UTC, yang-wang-ds commented
added support for feature events and newsletter block

2021-07-21 13:53 UTC, johnbxu requested changes

2021-07-21 13:53 UTC, johnbxu commented on events/models.py
> +            return '(UTC' + offset[:3] + ':' + offset[3:] + ')'
I think use a `f` string here instead of concatinating.

2021-07-21 16:22 UTC, yang-wang-ds commented on events/models.py
> +            return '(UTC' + offset[:3] + ':' + offset[3:] + ')'
updated

2021-07-23 13:17 UTC, merged