Webpack
CIGIHub/cigionline pull request #371
Opened 2020-10-01 16:03 UTC by franciscawebisoft

Tested webpack with new db

2020-10-02 18:06 UTC, gabrieltanchen requested changes
@willmtl I added the bundles to gitignore. Quick feedback - the bundled CSS ballooned from 19.7kB to 13.5MB. Part of this is the way you changed how fontawesome is imported, the other part is Bootstrap - we should only be importing what we need here.
![Screen Shot 2020-10-02 at 1 59 35 PM](https://user-images.githubusercontent.com/10100465/94955196-33885b80-04b8-11eb-985d-60e4c769f441.png)

@franciscawebisoft Please fix the comments from the linter.

2020-10-02 18:19 UTC, gabrieltanchen commented
Additionally, if we're switching to yarn, we should switch completely. There's no point in having `package-lock` and `yarn-lock`. Travis CI already supports yarn, so there shouldn't be a need to install yarn in the test script.

2020-10-02 18:27 UTC, gabrieltanchen commented
@franciscawebisoft Also, please use 2-space indents for the template files.

2020-10-05 18:32 UTC, gabrieltanchen requested changes
@franciscawebisoft There's a lot of hardcoded data in the templates - is this something you want to fix in the PR's for each task?

2020-10-05 18:32 UTC, gabrieltanchen commented on .npmrc
> +//npm.fontawesome.com/:_authToken=427F3299-460E-4ED4-A4F2-66902C07BD92
This is our private token and shouldn't have been committed. Please revert this change, and we'll need to regenerate a token from Fontawesome.

2020-10-05 18:32 UTC, gabrieltanchen commented on cigionline/static/css/global/_bootstrap_variables_overwrite.scss
> +//$grid-breakpoints: (
Remove this empty file.

2020-10-05 18:32 UTC, gabrieltanchen commented on cigionline/static/css/cigionline.scss
> -@import 'normalize';
What was the reason to remove normalize here?

2020-10-05 18:32 UTC, gabrieltanchen commented on cigionline/static/css/global/_mixins.scss
> +    background-image: url('https://www.cigionline.org/sites/default/files/styles/person_square/public/images/square/Aaronson_Susan-Square.jpg?itok=SrzaGYMm');
Don't add this default - if an image is missing it can lead to confusing results.

2020-10-05 19:15 UTC, franciscawebisoft commented on cigionline/static/css/global/_bootstrap_variables_overwrite.scss
> +//$grid-breakpoints: (
this file will not be empty eventually because i need to find a way to modify bootstrap breakpoints and have them match accordingly to your css media breakpoints which i have not been able to do yet

2020-10-05 22:09 UTC, willmtl commented on cigionline/static/css/cigionline.scss
> -@import 'normalize';
It's included in bootstrap.

2020-10-05 22:10 UTC, willmtl commented on .npmrc
> +//npm.fontawesome.com/:_authToken=427F3299-460E-4ED4-A4F2-66902C07BD92
Fixed it, sorry about that.

2020-10-06 01:03 UTC, gabrieltanchen approved these changes

2020-10-06 01:03 UTC, merged