CIGI-180, 181: Populate image and blockquote paragraph types with data
CIGIHub/cigionline pull request #399
Opened 2020-10-09 02:34 UTC by johnbxu

- Replaced placeholder text with template variables 
- Created basic publication page template for testing paragraphs

2020-10-09 12:47 UTC, gabrieltanchen requested changes

2020-10-09 12:47 UTC, gabrieltanchen commented on core/models.py
> +        ('image', ImageChooserBlock(template='streams/paragraph_type_image.html')),
Add these to the streams app, similar to how I implemented `ParagraphBlock`, based of [this tutorial](https://learnwagtail.com/tutorials/how-add-basic-streamfield-your-wagtail-cms-page/).

2020-10-09 15:12 UTC, johnbxu commented
Created blocks in stream app.

2020-11-16 19:25 UTC, gabrieltanchen commented
@johnbxu Sorry for taking so long to get back to this, can you resolve the merge conflicts?

2020-11-28 02:10 UTC, gabrieltanchen requested changes
I merged the latest changes in, and dealt with merging the migrations.

I renamed the classes in the `streams` app since "Paragraph" is very Drupal-focused while here we're creating StreamField blocks.

I also created a basic template for article pages so that we can test them.

A couple things I'll leave for you to work on:
1. The block templates need container sizes. We're not setting a container around the whole body since that will make it easier for us to create flows of blocks with varying containers, and even full-bleed containers for images like in the [smart city longform](https://www.cigionline.org/articles/searching-smart-citys-democratic-future).
2. When viewing a page with an image block, Django is returning an error that the `image` template tag is expecting an image but it's being passed a struct. That's because the `ImageBlock` class is a struct, so we need to pass the image within to the template tag instead.

2020-11-28 02:10 UTC, gabrieltanchen commented on templates/streams/image_block.html
> +<div class="paragraph-type-image">
This needs a container.

2020-11-28 02:10 UTC, gabrieltanchen commented on templates/streams/block_quote_block.html
> +<div class="paragraph-type-bloquote">
This needs a container.

2020-11-28 02:10 UTC, gabrieltanchen commented on templates/streams/block_quote_block.html
> +    <div class="paragraph-type-blockquote-author">
Indent within a condition.

2020-11-28 02:10 UTC, gabrieltanchen commented on templates/streams/block_quote_block.html
> +    <div class="paragraph-type-blockquote-author-title">
Indent within a condition.

2020-11-28 02:10 UTC, gabrieltanchen commented on templates/streams/block_quote_block.html
> +    <a href="{{ self.link_url }}" class="paragraph-type-blockquote-link">
Indent within a condition.

2020-12-01 01:33 UTC, gabrieltanchen commented
resolves CIGIHub/cigi-tickets#180
resolves CIGIHub/cigi-tickets#181

2020-12-01 20:39 UTC, johnbxu commented
Styled block quote to match live site, and added containers.

2020-12-05 02:51 UTC, gabrieltanchen approved these changes
Great job on this @johnbxu

2020-12-05 02:52 UTC, merged