CIGI-178b: Add data to related files component
CIGIHub/cigionline pull request #400
Opened 2020-10-09 16:30 UTC by johnbxu

- Added file data to basic page related files component
- Use http://127.0.0.1:8000/about/strategic-plan/ to test

2020-11-28 03:18 UTC, gabrieltanchen requested changes
This looks really good. Just a few little changes.

2020-11-28 03:18 UTC, gabrieltanchen commented on templates/includes/core_related_files_table.html
> +        <a href="{{file_block.value.url}}" title="{{file_block.value.title}}">
I don't think the `title` attribute is necessary here as it's not providing additional context in the tooltip. In fact, it might hurt us for SEO since it is duplicated content.

2020-11-28 03:18 UTC, gabrieltanchen commented on templates/includes/core_related_files_table.html
>      <tr>
Indent within a condition.

2020-11-28 03:18 UTC, gabrieltanchen commented on templates/core/basic_page.html
> +{% include "includes/hero_standard.html" with title=self.title subtitle=self.subtitle submenu=self.submenu %}
Indent within a condition.

2020-11-28 03:18 UTC, gabrieltanchen commented on templates/core/basic_page.html
> +    {% include_block block %}
Indent within a condition.

2020-11-30 17:32 UTC, johnbxu commented
Fixed indentations

2020-11-30 20:47 UTC, gabrieltanchen approved these changes

2020-11-30 20:47 UTC, merged