(Draft) CIGI-207: Add AJAX to multimedia list page
CIGIHub/cigionline pull request #522
Opened 2020-12-03 17:58 UTC by johnbxu

#### Description of changes
resolves CIGIHub/cigi-tickets#207

2020-12-07 14:29 UTC, gabrieltanchen requested changes

2020-12-07 14:29 UTC, gabrieltanchen commented on templates/base.html
> +    {% block extra_bundles %}
This is great. Please remove the `extra_css` and `extra_js` blocks as they won't be needed.

2020-12-07 14:29 UTC, gabrieltanchen commented on cigionline/static/multimedia_list_page.js
> +  function paginate() {
Most of this will need to be reused across many pages, so break out this function into its own file that'll be imported wherever it's needed. Parameters should be the div id for where the results will be displayed, the AJAX URL, etc.

At the top of the file, also document what's needed, for example, the `.loader-spinner` div in the template.

2020-12-07 14:29 UTC, gabrieltanchen commented on cigionline/static/css/includes/_pagination.scss
> +.pagination-links-numbered {
Rename this file to `pagination_numbered`, the same as the template. A component should have a one-to-one scss file that only contains the styling for the component.

2020-12-07 17:47 UTC, johnbxu commented
Moved function to module, and renamed scss file.

2020-12-08 21:58 UTC, gabrieltanchen commented
Closing as this is now done in #542

2020-12-08 21:58 UTC, closed without merging