Cigi 219
CIGIHub/cigionline pull request #525
Opened 2020-12-04 15:11 UTC by zylene

#### Description of changes
resolves CIGIHub/cigi-tickets#219

Created a template for publication hero with individual templates for topics, authors, date and share links.

2020-12-05 02:13 UTC, gabrieltanchen requested changes
This looks really great so far. You've brought over the styling from Drupal. Most of the comments here are dealing with moving towards a component-based approach to avoid a lot of development bugs that we encounter.

There are also a number of linting errors. You can see the tests that run within this PR. If there's a red cross on any of the checks, it'll require your attention. Let me know if you have any questions regarding any of the checks.

2020-12-05 02:13 UTC, gabrieltanchen commented on templates/includes/hero_publication.html
> +      {% include "includes/topics.html" with topics=self.topics %}
Use consistent identations - 2 spaces for everything except Python.

2020-12-05 02:13 UTC, gabrieltanchen commented on cigionline/static/css/pages/_publication.scss
> +        .date {
This needs to be split out for the date component.

2020-12-05 02:13 UTC, gabrieltanchen commented on templates/publications/publication_page.html
> +{% include "includes/hero_publication.html" with title=self.title  subtitle=self.subtitle authors=self.authors date=self.publishing_date download=self.pdf_downloads topics=self.topics %}
Indent within a block.

2020-12-05 02:13 UTC, gabrieltanchen commented on templates/publications/publication_page.html
> +{% block body_class %}publication-page{% endblock %}
Remove this body class - ideally it's only added if we _really_ need it, but I don't think that's the case here. If the body class is present it's far too easy to simply style by page type rather than by component. Drupal is mostly styled this way, and that's lead to issues with us changing some styling and a completely different part of the website breaks. A page should be made up of predictable components.

2020-12-08 13:46 UTC, gabrieltanchen commented
@zylene is this ready for review again?

2020-12-08 15:10 UTC, zylene commented
> @zylene is this ready for review again?

Yes,thank you

2020-12-08 22:17 UTC, gabrieltanchen requested changes

2020-12-08 22:17 UTC, gabrieltanchen commented on cigionline/static/css/pages/_publication.scss
> +section {
This file should be moved to `/static/css/include/_hero_publication.scss` to match with the template.

2020-12-08 22:17 UTC, gabrieltanchen commented on templates/includes/social_links.html
> +    <li class="facebook">
Use 2-space indents.

2020-12-08 22:17 UTC, gabrieltanchen commented on templates/includes/hero_publication.html
> +              <i class="fa fas fa-download"></i>
Use 2-space indents.

2020-12-08 22:17 UTC, gabrieltanchen commented on templates/includes/topics.html
> +    {% for topic in topics.all %}
Use 2-space indents.

2020-12-08 22:17 UTC, gabrieltanchen commented on templates/publications/publication_page.html
> +{{ pdf_downloads}}
Needs a space before the trailing bracket.

2020-12-08 22:17 UTC, gabrieltanchen commented on core/templatetags/core_tags.py
> +    return value.replace(' ', '+')
Use 2-space indents.

2020-12-08 22:17 UTC, gabrieltanchen commented on templates/includes/hero_publication.html
> +              {% if document.value.button_text == '' %}PDF Download {% else %} {{ document.value.button_text}} {% endif %}
On Drupal this reads "Download PDF". The button text and icon look a little large here.

2020-12-08 22:17 UTC, gabrieltanchen commented on templates/includes/social_links.html
> +        <a class="facebook-share-link fa-stack" data-url="{{ request.build_absolute_uri|slice:':-1' }}">
Add a `cursor: pointer` style to this class, so that the hover is the same as the other social buttons.

2020-12-08 22:17 UTC, gabrieltanchen commented on templates/includes/hero_publication.html
> +  <div class="container-sm hero-container">
Unnecessary wrapper element, these classes can be added to the `<section>` above.

2020-12-08 22:17 UTC, gabrieltanchen commented on cigionline/static/css/pages/_publication.scss
> +    .authors {
This needs to be broken out to `/static/css/includes/_authors.scss` to match with the template.

2020-12-08 22:17 UTC, gabrieltanchen commented on cigionline/static/css/pages/_publication.scss
> +    .topics {
This needs to be broken out to `/static/css/includes/_topics.scss` to match with the template.

2020-12-09 16:23 UTC, zylene commented
ready for re-review

2020-12-09 23:02 UTC, gabrieltanchen approved these changes

2020-12-09 23:16 UTC, merged