(draft) GIGI-208: Create large feature template
CIGIHub/cigionline pull request #536
Opened 2020-12-07 18:39 UTC by johnbxu

#### Description of changes
resolves CIGIHub/cigi-tickets#208

2020-12-08 13:46 UTC, gabrieltanchen requested changes

2020-12-08 13:46 UTC, gabrieltanchen commented on templates/includes/features/feature_content_large.html
> +<article class="feature-content feature-content-large feature-content-{{content|page_type}}">
Don't add the class based on page type. As far as I can tell you're not using it.

Reasoning: Any styling logic needs to be passed down to the component. For example, let's say we wanted the title for opinions to be smaller because of how long they were on average. It's more explicit to pass a class into this component like `small-title` than to have the font size passively be changed based on page type in the CSS.

2020-12-08 13:46 UTC, gabrieltanchen commented on templates/includes/features/feature_content_large.html
> +      {% include 'includes/features/feature_content_title.html' with title=content.feature_title %}
This logic should go in the `feature_content_title` component. Don't do the logic beforehand and then pass in the correct title. Give the component the `content` object and let it figure out what to display.

2020-12-08 13:46 UTC, gabrieltanchen commented on templates/includes/features/feature_content_large.html
> +      {% include 'includes/features/feature_content_subtitle.html' with subtitle=content.feature_subtitle %}
Same comment here as feature title.

2020-12-08 13:46 UTC, gabrieltanchen commented on templates/includes/features/feature_content_large.html
> +    {% if content|page_type|in_list:'opinion,publication' %}
Also the same here, the `feature_content_people` component should contain this logic.

2020-12-08 20:20 UTC, johnbxu commented
Moved logic to individual templates

2020-12-08 22:25 UTC, gabrieltanchen requested changes

2020-12-08 22:25 UTC, gabrieltanchen commented on cigionline/static/css/includes/_features.scss
> +  .feature-content-topic-list {
This files needs to be broken out to match with the templates. If a template needs styling, it should get its own scss file.

2020-12-08 22:25 UTC, gabrieltanchen commented on templates/includes/features/feature_content_large.html
> +    <p class="feature-content-date meta">{{ content.publishing_date|date:"F m, Y" }}</p>
Date is wrong here, I believe `m` is also month, and `j` is day.

2020-12-09 16:17 UTC, johnbxu commented
Broke up features scss into individual files, and updated date format

2020-12-10 00:58 UTC, gabrieltanchen approved these changes

2020-12-10 00:58 UTC, merged