Cigi 219b
CIGIHub/cigionline pull request #538
Opened 2020-12-07 19:51 UTC by zylene

#### Description of changes
resolves CIGIHub/cigi-tickets#219

Adds about the authors template, includes this template for publications, events and articles. Sends variable for speaker or author and pluralizes for multiple.

2020-12-08 22:32 UTC, gabrieltanchen requested changes

2020-12-08 22:32 UTC, gabrieltanchen commented on templates/includes/about_the_author.html
> +    <div class="container-sm">
Use 2-space indents.

2020-12-08 22:32 UTC, gabrieltanchen commented on templates/publications/publication_page.html
> +        {% include "includes/about_the_author.html" with authors=self.authors type=type %}
Use 2-space indents.

2020-12-08 22:32 UTC, gabrieltanchen commented on templates/includes/about_the_author.html
> +                    <div class="name">{{ author.value.first_name }}  {{ author.value.last_name }}</div>
1. Use the author page title here rather than the first and last names.
2. There should be a link here to the author page.
3. The font size and weight look a little large here compared to what's on production.

2020-12-08 22:32 UTC, gabrieltanchen commented on templates/events/event_page.html
> +    {% include "includes/hero_standard.html" with title=self.title %}
Use 2-space indents.

2020-12-09 15:55 UTC, zylene commented
changes made, ready for review

2020-12-10 01:13 UTC, gabrieltanchen approved these changes

2020-12-10 01:24 UTC, merged