Cigi 239: events hero
CIGIHub/cigionline pull request #583
Opened 2020-12-15 14:52 UTC by zylene

#### Description of changes
resolves CIGIHub/cigi-tickets#239
adding fields for events heros including styling for dropdown but not including ical feeds

2020-12-15 17:03 UTC, gabrieltanchen requested changes

2020-12-15 17:03 UTC, gabrieltanchen commented on templates/includes/hero_event.html
> +        <div class="col-md-3">
On production, the date circle is top aligned with the event title/topics. It should also be right aligned within the container.

![Screen Shot 2020-12-15 at 12 00 33 PM](https://user-images.githubusercontent.com/10100465/102246910-457d7600-3ecd-11eb-8e47-327b45f35f41.png)

2020-12-15 17:03 UTC, gabrieltanchen commented on cigionline/static/css/includes/_hero_event.scss
> +    .block-external_speaker {
This will need to be fixed in this PR. I can't merge this in will failing tests or else everybody's tests will fail.

2021-01-06 19:36 UTC, zylene commented on cigionline/static/css/includes/_hero_event.scss
> +    .block-external_speaker {
Adding the template didn't get around this problem and just added extra divs that don't serve a purpose. Solving with css.

2021-01-08 03:50 UTC, gabrieltanchen approved these changes
Looks great. We'll add the iCal implementation later.

2021-01-08 04:01 UTC, merged