CIGI-208: Add feature medium component
CIGIHub/cigionline pull request #606
Opened 2020-12-17 16:50 UTC by johnbxu

#### Description of changes
resolves CIGIHub/cigi-tickets#208

![image](https://user-images.githubusercontent.com/40705848/102517188-bfdd0000-405d-11eb-88cf-ec133057f71f.png)

![image](https://user-images.githubusercontent.com/40705848/102517246-d08d7600-405d-11eb-88e3-883516233144.png)

- Create styling and template for featured medium component
- Added styling for multimedia button on large and medium featured components
- Use /opinions to test

2020-12-17 17:31 UTC, gabrieltanchen commented
@johnbxu failing tests

2020-12-17 18:37 UTC, johnbxu commented
Fixed migration as per instructions on https://docs.wagtail.io/en/stable/releases/2.11.html

2020-12-17 23:37 UTC, gabrieltanchen requested changes

2020-12-17 23:37 UTC, gabrieltanchen commented on articles/models.py
> +        'wagtailcore.Page',
Why is this changed to the general page?

2020-12-18 00:47 UTC, johnbxu commented on articles/models.py
> +        'wagtailcore.Page',
It's for testing different featurable content on the opinion landing page, ex. multimedia.

2020-12-18 16:29 UTC, johnbxu commented on articles/models.py
> +        'wagtailcore.Page',
I changed this back to ArticlePage and added a featured_content field to HomePage to test out featured content. This broke some tests that needed a homepage fixture though. I'll look into fixing it after finishing the drupal promotion blocks.

2020-12-18 16:48 UTC, gabrieltanchen commented
@johnbxu don't worry about adding featured content to the HomePage. I'm already working on that. Just reverting the ArticleListPage featured content foreign key to ArticlePage is good enough.

2020-12-21 15:51 UTC, johnbxu commented
Removed home page feature and reverted featured_article model back to ArticlePage.

2020-12-21 16:12 UTC, gabrieltanchen approved these changes

2020-12-21 16:12 UTC, merged