CIGI-387: Implement WTO series in the series section
CIGIHub/cigionline pull request #794
Opened 2021-01-18 16:31 UTC by johnbxu

#### Description of changes
resolves CIGIHub/cigi-tickets#387

Test:
/modernizing-world-trade-organization/
/articles/recalibrating-wto-dispute-settlement-system-strengthening-panel-stage/
/multimedia/video-moving-forward-wtos-dispute-settlement-paralysis/

![image](https://user-images.githubusercontent.com/40705848/104940952-73e4ea00-5980-11eb-9452-e8fabc9a0ec8.png)

2021-01-18 18:30 UTC, gabrieltanchen requested changes
On production, the article hover colour is black on the series page (CIGI red on the article page). The hover colour for the author is black on both pages.

2021-01-18 18:48 UTC, johnbxu commented
> On production, the article hover colour is black on the series page (CIGI red on the article page). The hover colour for the author is black on both pages.

I think these are more likely errors rather than design elements. The article hover colour should probably be consistent across pages, and the author hover colour was likely not put in by accident. Do you think I should still reproduce prod exactly?

2021-01-19 18:07 UTC, johnbxu commented
Updated hover colours

2021-01-19 18:19 UTC, gabrieltanchen approved these changes

2021-01-19 18:47 UTC, merged