Cigi 362, 363, 364, 365 - cyber series article elements
CIGIHub/cigionline pull request #815
Opened 2021-01-20 16:54 UTC by zylene

#### Description of changes
resolves CIGIHub/cigi-tickets#362
resolves CIGIHub/cigi-tickets#363
resolves CIGIHub/cigi-tickets#364
resolves CIGIHub/cigi-tickets#365

Drop caps, pull quote, external quote and end of article marker.
Does not include scroll in effect for pull quote as this had an external library dependency.

2021-01-25 00:26 UTC, zylene commented
The scroll reveal has been added.
Just noticed there is not styling for pull quotes and I don't seem to be able to find any on this series so only the elements noted have been styled.

2021-01-25 17:35 UTC, gabrieltanchen requested changes
There are also linting errors.

2021-01-25 17:35 UTC, gabrieltanchen commented on cigionline/static/themes/cyber_series/index.js
> +sr.reveal('.stream-block-blockquote', {
I think this needs to be updated, this looks like it will error out, since you're setting `sr` to be null in the line above.

2021-01-25 21:22 UTC, zylene commented on cigionline/static/themes/cyber_series/index.js
> +sr.reveal('.stream-block-blockquote', {
fix uploaded.

2021-01-26 14:31 UTC, gabrieltanchen approved these changes
👍

2021-01-26 14:32 UTC, merged