Cigi 372b: cyberseries article series
CIGIHub/cigionline pull request #844
Opened 2021-01-25 00:03 UTC by zylene

#### Description of changes
resolves CIGIHub/cigi-tickets#cigi-372
resolves CIGIHub/cigi-tickets#cigi-373

Adding in the series for article and article series pages
fixes for background image on article page.

2021-01-25 18:02 UTC, gabrieltanchen requested changes

2021-01-25 18:02 UTC, gabrieltanchen commented on templates/themes/cyber_series/includes/in_the_series.html
> +              <h5 class="article-title"><a {% if block.value.id == article_id %}class="active"{% endif %} href="{{ block.value.url }}">{{ block.value.title }}</a></h5>
Don't include an `a` tag for the current article.

2021-01-25 21:23 UTC, zylene commented on templates/themes/cyber_series/includes/in_the_series.html
> +              <h5 class="article-title"><a {% if block.value.id == article_id %}class="active"{% endif %} href="{{ block.value.url }}">{{ block.value.title }}</a></h5>
removed active class

2021-01-26 14:50 UTC, gabrieltanchen approved these changes

2021-01-26 15:08 UTC, merged