Cigi 412
CIGIHub/cigionline pull request #862
Opened 2021-01-27 21:03 UTC by johnbxu

#### Description of changes
resolves CIGIHub/cigi-tickets#412

![image](https://user-images.githubusercontent.com/40705848/106053727-228fd580-60b9-11eb-9ed8-4076b848a0b0.png)
![image](https://user-images.githubusercontent.com/40705848/106053751-2885b680-60b9-11eb-9f3e-828a3e3a9e62.png)

2021-01-28 17:16 UTC, gabrieltanchen requested changes

2021-01-28 17:16 UTC, gabrieltanchen commented on promotions/models.py
> +class PromotionBlockPage(Page):
Promotion blocks shouldn't need to be a page, or need a list page. These can be created as a Django model.

2021-01-29 16:53 UTC, johnbxu commented
Changed page model to django model

2021-02-01 15:29 UTC, gabrieltanchen approved these changes
👍

2021-02-01 15:40 UTC, merged