CIGI-421: Add featured events markup and styling
CIGIHub/cigionline pull request #870
Opened 2021-01-28 16:51 UTC by johnbxu

#### Description of changes
resolves CIGIHub/cigi-tickets#421

![image](https://user-images.githubusercontent.com/40705848/106171032-1bbb9e00-615f-11eb-8e4c-fb4ee00850b2.png)
![image](https://user-images.githubusercontent.com/40705848/106171054-21b17f00-615f-11eb-955c-ed5de7dd4274.png)

2021-01-28 19:08 UTC, gabrieltanchen requested changes

2021-01-28 19:08 UTC, gabrieltanchen commented on templates/events/event_list_page.html
> +        {% if forloop.counter == 1 or forloop.counter == 4 %}
These opening and closing div conditions only work if there are exactly 6 featured events. It's fine to wrap this in a single row and let the columns expand to their own rows when necessary.

2021-01-28 20:18 UTC, johnbxu commented
Removed the rows and updated styling.

2021-01-29 13:19 UTC, gabrieltanchen approved these changes

2021-01-29 13:39 UTC, merged