CIGI-437: Implement article landing page series swiper section
CIGIHub/cigionline pull request #896
Opened 2021-02-03 03:02 UTC by johnbxu

#### Description of changes
resolves CIGIHub/cigi-tickets#issue_number

- The series order is off because on the Drupal site some series don't have publishing date filled out. Need to update Drupal site with dates and then migrate

![image](https://user-images.githubusercontent.com/40705848/106691767-14065a00-65a2-11eb-8802-b2be9e6da071.png)
![image](https://user-images.githubusercontent.com/40705848/106691879-2bddde00-65a2-11eb-812c-0d3f4851aa38.png)

2021-02-05 15:08 UTC, gabrieltanchen requested changes

2021-02-05 15:08 UTC, gabrieltanchen commented on articles/models.py
> +            article_series.append(series.specific)
You should be able to just return the queryset here. Since you're already querying `ArticleSeriesPage`, you don't need to call `.specific`.

2021-02-06 03:57 UTC, johnbxu commented
Haha good call 😆 . Changed to return queryset.

2021-02-08 14:53 UTC, gabrieltanchen approved these changes

2021-02-08 14:53 UTC, merged